evaluate-commands %sh{
  for file in "$HOME"/.config/kak/*.kak; do
    printf "%s\n" "try %{
      source '$file'
      echo -debug 'Sourced $file'
    } catch %{
      echo -debug %val{error}
    } catch %{
      echo -debug 'Error sourcing $file'
    }"
  done
}
