[
  ./programs/alacritty.nix
  ./programs/borg-backup.nix
  ./programs/fish.nix
  ./programs/git.nix
  ./programs/hammerspoon.nix
  ./programs/helix.nix
  ./programs/kakoune.nix
  ./programs/karabiner.nix
  ./programs/kitty.nix
  ./programs/mercurial.nix
  ./programs/neovim.nix
  ./programs/nix.nix
  ./programs/skhd.nix
  ./programs/starship.nix
  ./programs/sway.nix
  ./programs/tmux.nix
  ./programs/vis.nix
  ./programs/wezterm.nix
  ./programs/xmonad.nix
  ./programs/yabai.nix
]
