#!/usr/bin/env bash

error() {
  echo -e "ERROR: $*" >&2
  exit 1
}

# Error and exit if stow isn't installed
command -v stow >/dev/null 2>&1 || error "stow is not installed"

if [ $# -gt 0 ]; then
  # Create config folders if they don't already exist
  for i in "$@"; do
    case $i in

      alacritty   ) (set -x; mkdir -p "$HOME/.config/alacritty");;
      bspwm       ) (set -x; mkdir -p "$HOME/.config/bspwm");;
      compton     ) (set -x; mkdir -p "$HOME/.config/compton");;
      fish        ) (set -x; mkdir -p "$HOME/.config/fish/functions");;
      hammerspoon ) (set -x; mkdir -p "$HOME/.hammerspoon");;
      kakoune     ) (set -x; mkdir -p "$HOME/.config/kak");;
      karabiner   ) (set -x; mkdir -p "$HOME/.config/karabiner");;
      kitty       ) (set -x; mkdir -p "$HOME/.config/kitty");;
      mpd         ) (set -x; mkdir -p "$HOME/.config/mpd");;
      ncmpcpp     ) (set -x; mkdir -p "$HOME/.config/ncmpcpp");;
      neovim      ) (set -x; mkdir -p "$HOME/.config/nvim");;
      polybar     ) (set -x; mkdir -p "$HOME/.config/polybar");;
      ranger      ) (set -x; mkdir -p "$HOME/.config/ranger");;
      redshift    ) (set -x; mkdir -p "$HOME/.config/redshift");;
      sxhkd       ) (set -x; mkdir -p "$HOME/.config/sxhkd");;
      xmonad      ) (set -x; mkdir -p "$HOME/.config/xmonad");;
      zathura     ) (set -x; mkdir -p "$HOME/.config/zathura");;

      *           ) ;;
    esac
  done
  (set -x; stow --target "$HOME" -S "$@")
else
  error "No packages specified\nUsage:  ./install [PACKAGES]"
fi
