#!/usr/bin/env bash

folder() { (set -x; mkdir -p "$1") }

if ! [ -x "$(command -v stow)" ]; then
  echo 'ERROR: stow is not installed' >&2
  exit 1
fi

if [ $# -gt 0 ]; then
  for i in "$@"; do
    case $i in
      bspwm )
        folder "$HOME/.config/bspwm/";;
      fish )
        folder "$HOME/.config/fish/functions/";;
      hammerspoon )
        folder "$HOME/.hammerspoon/";;
      kakoune )
        folder "$HOME/.config/kak/";;
      neovim )
        folder "$HOME/.config/nvim/";;
      sxhkd )
        folder "$HOME/.config/sxhkd/";;
      vscode )
        folder "$HOME/Library/Application Support/Code/User/";;
      xmonad )
        folder "$HOME/.config/xmonad/";;
      * )
        ;;
    esac
  done
  (set -x; stow --target "$HOME" -S "$@")
else
  echo "ERROR: No arguments" >&2
  exit 1
fi
