file_watch_support = false
snippet_support = false
verbosity = 2

[server]
timeout = 0

[language_server.static-ls]
filetypes = ["haskell"]
roots = ["*.cabal", "cabal.project", "package.yaml"]
command = "static-ls"

[language_server.rust-analyzer]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "sh"
args = ["-c", 'if path=$(rustup which rust-analyzer 2>/dev/null); then exec "$path"; else exec rust-analyzer; fi']
[language_server.rust-analyzer.settings.rust-analyzer]
check.command = "clippy"
