set --global --export --prepend PATH "/nix/var/nix/profiles/default/bin"
set --global --export --prepend PATH "$HOME/.nix-profile/bin"
set --global --export COLORTERM "$TERM"
set --global --export EDITOR "nvim"
set --universal FZF_LEGACY_KEYBINDINGS 0
set --universal FZF_DEFAULT_OPTS "--color=light --height=40% --layout=reverse --exact"
set --universal FZF_CD_COMMAND "fd --type directory --follow --exclude '.git' . \$dir"
set --universal FZF_CD_WITH_HIDDEN_COMMAND "fd --type directory --follow --exclude '.git' --hidden . \$dir"
set --universal FZF_FIND_FILE_COMMAND "fd --type file --follow --exclude '.git' --hidden . \$dir"
set --universal FZF_OPEN_COMMAND "fd --type file --follow --exclude '.git' --hidden . \$dir"
alias ls "ls --color=auto"
set --global fish_greeting ""
