#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

cache_dir="$HOME/.cache/nix-index"
system=$(nix eval --expr 'builtins.currentSystem' --impure --raw)
release=${1:-latest}
filename="index-$system"
url="https://github.com/nix-community/nix-index-database/releases/download/${release:-latest}/${filename}"

mkdir -p "$cache_dir"
curl --fail -L "$url" -o "$cache_dir/$filename"
ln -sf "$filename" "$cache_dir/files"
