#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

if [ "$(nix-instantiate --eval --expr 'builtins ? getFlake' --json)" = "true" ]; then
  home-manager --flake ".#$(hostname -s)" "$@"
else
  if [ "$1" = "build" ]; then
    nix-build --attr "homeConfigurations.$(hostname -s).activationPackage"
  elif [ "$1" = "switch" ]; then
    result=$(nix-build --attr "homeConfigurations.$(hostname -s).activationPackage" --no-out-link)
    "$result/activate"
  else
    echo "usage: home-rebuild (build | switch)" >&2
    exit 1
  fi
fi
