#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

columns=$(tput cols)
lines=$(tput lines)

if [ "${columns}" -lt 50 ] || [ "${lines}" -lt 30 ]; then
  preview=(--no-preview)
else
  if [ "${columns}" -ge 150 ]; then
    position="right"
    size="60%"
    border="left"
  else
    position="down"
    size="70%"
    border="top"
  fi

  preview=(\
    --preview "echo {} | awk '{print \$2}' | xargs jj show --color=always | delta" \
    --preview-window "${position},${size},border-${border}" \
  )
fi

  jj ll \
  --no-graph \
  --color=always \
| fzf -1 -0 \
  --exact \
  --query="$*" \
  --no-sort \
  --reverse \
  --height=100% \
  --info=hidden \
  "${preview[@]}" \
  --ansi \
  --color=light \
| awk '{print $2}' \
| xargs git rev-parse --verify --quiet
