"escape" = { fg = "yellow_900" }

"type" = { fg = "blue_500" }

# "constant" = { fg = "black", bg = "white", modifiers = [] }
# "constant.builtin" = { fg = "black", bg = "white", modifiers = [] }
"constant.builtin.boolean" = { fg = "green_500" }
"constant.character" = { fg = "yellow_800" }

"number" = { fg = "green_500" }

"string" = { fg = "yellow_800" }

"comment" = { fg = "gray_500" }

"variable" = { fg = "black", bg = "white", modifiers = [] }
# "variable.builtin" = { fg = "black", bg = "white", modifiers = [] }
# "variable.parameter" = { fg = "black", bg = "white", modifiers = [] }
# "variable.property" = { fg = "black", bg = "white", modifiers = [] }
# "variable.function" = { fg = "black", bg = "white", modifiers = [] }

"label" = { fg = "black", bg = "white", modifiers = [] }

"punctuation" = { fg = "black", bg = "white", modifiers = [] }
# "punctuation.delimiter" = { fg = "black", bg = "white", modifiers = [] }
# "punctuation.bracket" = { fg = "black", bg = "white", modifiers = [] }

"keyword" = { fg = "red_600" }
# "keyword.control" = { fg = "black", bg = "white", modifiers = [] }
# "keyword.control.conditional" = { fg = "black", bg = "white", modifiers = [] }
# "keyword.control.conditional.repeat" = { fg = "black", bg = "white", modifiers = [] }
# "keyword.control.conditional.import" = { fg = "black", bg = "white", modifiers = [] }
# "keyword.directive" = { fg = "black", bg = "white", modifiers = [] }
# "keyword.function" = { fg = "black", bg = "white", modifiers = [] }

"operator" = { fg = "orange_600" }

"function" = { fg = "purple_500" }
# "function.builtin" = { fg = "black", bg = "white", modifiers = [] }
# "function.method" = { fg = "black", bg = "white", modifiers = [] }
"function.macro" = { fg = "green_600", bg = "white", modifiers = [] }
# "function.special" = { fg = "black", bg = "white", modifiers = [] }

"tag" = { fg = "black", bg = "white", modifiers = [] }

"namespace" = { fg = "purple_500", bg = "white", modifiers = [] }

"ui.background" = { fg = "black", bg = "white", modifiers = [] }

"ui.cursor" = { fg = "red_100", bg = "pink_500" }
"ui.cursor.insert" = { fg = "black", bg = "yellow_500" }
"ui.cursor.select" = { fg = "black", bg = "yellow_500" }
"ui.cursor.match" = { fg = "black", bg = "yellow_500" }
"ui.cursor.primary" = { fg = "black", bg = "yellow_500" }

"ui.linenr" = { fg = "gray_500", bg = "gray_100" }
"ui.linenr.selected" = { fg = "black", bg = "gray_100" }

"ui.statusline" = { fg = "black", bg = "gray_100", modifiers = [] }
"ui.statusline.inactive" = { fg = "black", bg = "gray_100", modifiers = [] }

"ui.popup" = { fg = "black", bg = "gray_100", modifiers = [] }

"ui.window" = { fg = "black", bg = "white", modifiers = [] }

"ui.help" = { fg = "black", bg = "white", modifiers = [] }

"ui.text" = { fg = "black", bg = "white", modifiers = [] }
"ui.text.focus" = { fg = "black", bg = "white", modifiers = [] }

"ui.info" = { fg = "black", bg = "gray_100", modifiers = [] }
"ui.info.text" = { fg = "black", bg = "gray_100", modifiers = [] }

"ui.menu" = { fg = "black", bg = "gray_100", modifiers = [] }
"ui.menu.selected" = { fg = "white", bg = "blue_500", modifiers = [] }

"ui.selection" = { bg = "red_100" }
"ui.selection.primary" = { bg = "yellow_200" }

"info" = { fg = "black", bg = "white", modifiers = [] }
"hint" = { fg = "black", bg = "white", modifiers = [] }
"warning" = { fg = "black", bg = "white", modifiers = [] }
"error" = { fg = "black", bg = "white", modifiers = [] }


[palette]

black = "#1b1f23"

white = "#ffffff"

gray_000 = "#fafbfc"
gray_100 = "#f6f8fa"
gray_200 = "#e1e4e8"
gray_300 = "#d1d5da"
gray_400 = "#959da5"
gray_500 = "#6a737d"
gray_600 = "#586069"
gray_700 = "#444d56"
gray_800 = "#2f363d"
gray_900 = "#24292e"

blue_000 = "#f1f8ff"
blue_100 = "#dbedff"
blue_200 = "#c8e1ff"
blue_300 = "#79b8ff"
blue_400 = "#2188ff"
blue_500 = "#0366d6"
blue_600 = "#005cc5"
blue_700 = "#044289"
blue_800 = "#032f62"
blue_900 = "#05264c"

green_000 = "#f0fff4"
green_100 = "#dcffe4"
green_200 = "#bef5cb"
green_300 = "#85e89d"
green_400 = "#34d058"
green_500 = "#28a745"
green_600 = "#22863a"
green_700 = "#176f2c"
green_800 = "#165c26"
green_900 = "#144620"

yellow_000 = "#fffdef"
yellow_100 = "#fffbdd"
yellow_200 = "#fff5b1"
yellow_300 = "#ffea7f"
yellow_400 = "#ffdf5d"
yellow_500 = "#ffd33d"
yellow_600 = "#f9c513"
yellow_700 = "#dbab09"
yellow_800 = "#b08800"
yellow_900 = "#735c0f"

orange_000 = "#fff8f2"
orange_100 = "#ffebda"
orange_200 = "#ffd1ac"
orange_300 = "#ffab70"
orange_400 = "#fb8532"
orange_500 = "#f66a0a"
orange_600 = "#e36209"
orange_700 = "#d15704"
orange_800 = "#c24e00"
orange_900 = "#a04100"

red_000 = "#ffeef0"
red_100 = "#ffdce0"
red_200 = "#fdaeb7"
red_300 = "#f97583"
red_400 = "#ea4a5a"
red_500 = "#d73a49"
red_600 = "#cb2431"
red_700 = "#b31d28"
red_800 = "#9e1c23"
red_900 = "#86181d"

purple_000 = "#f5f0ff"
purple_100 = "#e6dcfd"
purple_200 = "#d1bcf9"
purple_300 = "#b392f0"
purple_400 = "#8a63d2"
purple_500 = "#6f42c1"
purple_600 = "#5a32a3"
purple_700 = "#4c2889"
purple_800 = "#3a1d6e"
purple_900 = "#29134e"

pink_000 = "#ffeef8"
pink_100 = "#fedbf0"
pink_200 = "#f9b3dd"
pink_300 = "#f692ce"
pink_400 = "#ec6cb9"
pink_500 = "#ea4aaa"
pink_600 = "#d03592"
pink_700 = "#b93a86"
pink_800 = "#99306f"
pink_900 = "#6d224f"
