format = """\
  $jobs\
  $username\
  $directory\
  $git_branch\
  $git_commit\
  $git_status\
  $git_state\
  $status\
  $character\
"""
add_newline = false

[jobs]
disabled = false
format = '[+$number]($style) '
style = 'cyan'
threshold = 0

[username]
disabled = false

[directory]
disabled = false
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'blue'
read_only = ' '
read_only_style = 'blue'
truncation_length = 0
fish_style_pwd_dir_length = 1

[git_branch]
disabled = false
format = 'on [ $branch]($style) '
style = ''
only_attached = true

[git_commit]
disabled = false
format = '[$hash]($style) '
style = ''

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style) )'
style = ''
conflicted = '[=](cyan)'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '[?](red)'
stashed = '\$'
modified = '[~](red)'
staged = '[+](green)'
renamed = '[»](red)'
deleted = '[×](red)'

[git_state]
disabled = false
format = '[\[$state( $progress_current/$progress_total)\]]($style) '
style = 'cyan'

[status]
disabled = false
format = '[$status]($style) '
style = 'red'
recognize_signal_code = false

[character]
disabled = false
success_symbol = 'λ'
error_symbol = '[λ](red)'
