format = """\
  $jobs\
  $username\
  $directory\
  $git_branch\
  $git_commit\
  $git_status\
  $git_state\
  $nix_shell\
  $status\
  $character\
"""
add_newline = false

[jobs]
disabled = false
format = '[ $number]($style) '
style = 'cyan'
threshold = 0

[username]
disabled = false

[directory]
disabled = false
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'blue'
read_only = ' '
read_only_style = 'blue'
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
disabled = false
format = '(on [ $branch]($style)) '
style = 'blue'
only_attached = true

[git_commit]
disabled = false
format = '(at [ $hash]($style)) '
style = 'blue'

[git_status]
disabled = false
format = '([\($conflicted$staged$modified$renamed$deleted$untracked$ahead_behind$stashed\)]($style) )'
style = ''
conflicted = '[=$count](cyan)'
ahead = '[⇡$count](green)'
behind = '[⇣$count](red)'
diverged = '[⇡$ahead_count](green)[⇣$behind_count](red)'
untracked = '[?](red)'
stashed = '[\$](yellow)'
modified = '[~](red)'
staged = '[+](green)'
renamed = '[»](red)'
deleted = '[×](red)'

[git_state]
disabled = false
format = '[\($state( $progress_current/$progress_total)\)]($style) '
style = 'cyan'

[nix_shell]
disabled = false
format = 'via [${symbol}nix-shell]($style) '
symbol = ' '
style = 'blue'

[status]
disabled = false
format = '[$status]($style) '
style = 'red'
recognize_signal_code = false

[character]
disabled = false
success_symbol = 'λ'
error_symbol = '[λ](red)'
