alias gauntlet "~/Code/evan.relf/scripts/gauntlet/gauntlet"
alias qa "~/Code/evan.relf/scripts/qa/qa"
alias vpn "~/Code/evan.relf/scripts/vpn/vpn"
alias autocompile "~/Code/evan.relf/scripts/autocompile/autocompile"
abbr --add nr "npm run"
abbr --add sql "psql -d vetpro -U postgres -h localhost -p 5432"
