user.name = "Evan Relf"
user.email = "evan@evanrelf.com"
ui.diff.format = "git"
ui.diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]
ui.pager = "delta"
template-aliases.'format_timestamp(timestamp)' = 'timestamp.ago()'
