aliases.d = ['diff']
aliases.l = ['log', '-r', 'ancestors(present(@), 10) | (ancestors(immutable_heads().., 2) & mine()) | present(trunk()) | bookmarks()']
aliases.ll = ['log', '-r', 'ancestors(present(@)) | (ancestors(immutable_heads().., 2) & mine()) | present(trunk()) | bookmarks()']
aliases.par = ['parallelize']
aliases.s = ['status']

aliases.blame = ['file', 'annotate']
aliases.clone = ['git', 'clone']
aliases.fetch = ['git', 'fetch']
aliases.init = ['git', 'init']
aliases.push = ['git', 'push']
aliases.remote = ['git', 'remote']

aliases.mut = ['--ignore-immutable']
aliases.here = ['bookmark', 'set', '-r', '@-']
aliases.give = ['squash', '--use-destination-message', '--from', '@', '--into']
aliases.take = ['squash', '--use-destination-message', '--into', '@', '--from']

user.name = 'Evan Relf'
user.email = 'evan@evanrelf.com'
ui.default-command = 'l'
ui.graph.style = 'ascii'
ui.diff-formatter = ':git'
ui.diff-editor = ':builtin'
ui.merge-editor = 'mergiraf'
ui.pager = 'delta'
merge-tools.delta.diff-expected-exit-codes = [0, 1]
git.colocate = true
git.auto-local-bookmark = false
git.push-new-bookmarks = true
git.private-commits = 'subject(glob:"private:*") & mine()'
git.write-change-id-header = true
signing.behavior = 'own'
signing.backend = 'ssh'
signing.key = '~/.ssh/jj.pub'

revset-aliases.'pr(x)' = 'ancestors(x) ~ ancestors(trunk())' # TODO: Choose a better name

templates.git_push_bookmark = '"evanrelf/push-" ++ change_id.short()'
templates.log = 'evan_log_oneline'
template-aliases.'format_short_id(id)' = 'id.shortest(6)'
# TODO: `s/conflict/conflicted` label? From v0.33.0
# https://github.com/jj-vcs/jj/releases/tag/v0.33.0
template-aliases.evan_log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        format_short_commit_id(commit_id),
        pad_start(3, format_log_timestamp(commit_timestamp(self))),
        if(conflict, label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(signature)),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        if(empty, label("empty", "(empty)")),
        bookmarks,
        tags,
        working_copies,
      ) ++ "\n",
    ),
  ),
) ++
if(!description && !empty,
  diff.summary(),
)
'''
template-aliases.'ts(timestamp)' = 'timestamp.ago().remove_suffix(" ago").remove_suffix("s")'
template-aliases.'format_log_timestamp(t)' = '''
if(
  ts(t).ends_with("second"),
  ts(t).remove_suffix(" second") ++ label("timestamp", "s"),
if(
  ts(t).ends_with("minute"),
  ts(t).remove_suffix(" minute") ++ label("timestamp", "m"),
if(
  ts(t).ends_with("hour"),
  ts(t).remove_suffix(" hour") ++ label("timestamp", "h"),
if(
  ts(t).ends_with("day"),
  ts(t).remove_suffix(" day") ++ label("timestamp", "d"),
if(
  ts(t).ends_with("week"),
  ts(t).remove_suffix(" week") ++ label("timestamp", "wk"),
if(
  ts(t).ends_with("month"),
  ts(t).remove_suffix(" month") ++ label("timestamp", "mo"),
if(
  ts(t).ends_with("year"),
  ts(t).remove_suffix(" year") ++ label("timestamp", "yr"),
ts(t),
)))))))
'''
