aliases.ab = ['abandon']
aliases.b = ['bookmark']
aliases.c = ['commit']
aliases.d = ['diff']
aliases.dt = ['diff', '--tool', 'difft']
aliases.l = ['log', '-r', 'alias_l()']
aliases.ll = ['log', '-r', 'alias_ll()']
aliases.s = ['status']

aliases.blame = ['file', 'annotate']
aliases.clone = ['git', 'clone', '--colocate']
aliases.fetch = ['git', 'fetch']
aliases.push = ['git', 'push']

aliases.mut = ['--ignore-immutable']
aliases.here = ['bookmark', 'move', '--to', '@-']
aliases.give = ['squash', '--use-destination-message', '--from', '@', '--into']
aliases.take = ['squash', '--use-destination-message', '--into', '@', '--from']
aliases.invert = ['backout', '-d', '@-', '-r']

user.name = 'Evan Relf'
user.email = 'evan@evanrelf.com'
core.watchman.register_snapshot_trigger = true
ui.default-command = 'status'
ui.graph.style = 'ascii'
ui.diff.format = 'git'
ui.pager = 'delta'
merge-tools.delta.diff-expected-exit-codes = [0, 1]
merge-tools.difft.diff-args = ['--color=always', '$left', '$right']
ui.default-description = "\n"
ui.allow-filesets = true
git.auto-local-bookmark = false
git.push-new-bookmarks = true
git.subprocess = true

revset-aliases.'alias_l()' = 'latest(::@, 10) | (ancestors(immutable_heads().., 2) & remote_bookmarks().. & mine()) | heads(trunk()) | bookmarks()'
revset-aliases.'alias_ll()' = 'alias_l() | ::@'
revset-aliases.'pr(x)' = '::x ~ ::trunk()' # TODO: Choose a better name

templates.log = 'evan_log_oneline'
template-aliases.'format_short_id(id)' = 'id.shortest(6)'
template-aliases.evan_log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        format_short_commit_id(commit_id),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("second"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" second") ++ label("timestamp", "s"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("minute"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" minute") ++ label("timestamp", "m"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("hour"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" hour") ++ label("timestamp", "h"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("day"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" day") ++ label("timestamp", "d"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("week"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" week") ++ label("timestamp", "wk"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("month"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" month") ++ label("timestamp", "mo"),
        if(
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").ends_with("year"),
          committer.timestamp().ago().remove_suffix(" ago").remove_suffix("s").remove_suffix(" year") ++ label("timestamp", "yr"),
        committer.timestamp().ago().remove_suffix(" ago"),
        ))))))),
        if(conflict, label("conflict", "conflict")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        if(empty, label("empty", "(empty)")),
        bookmarks,
        tags,
        working_copies,
      ) ++ "\n",
    ),
  )
)
'''

[[--scope]]
--when.repositories = ["~/Code/MercuryTechnologies"]
[--scope.core]
fsmonitor = "watchman"
