#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

tmp=$(mktemp)

# Colon separators
cat <<EOF > "${tmp}"
xterm-24bit|xterm with 24-bit direct color mode,
  use=xterm-256color,
  setb24=\E[48:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
  setf24=\E[38:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
EOF
echo "Now you need to run Emacs with TERM=xterm-24bit"

# Semicolon separators
# cat <<EOF > "$tmp"
# xterm-24bits|xterm with 24-bit direct color mode,
#   use=xterm-256color,
#   setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
#   setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
# EOF
# echo "Now you need to run Emacs with TERM=xterm-24bits"

tic -x -o "${HOME}/.local/share/terminfo" "${tmp}"

rm -f "${tmp}"
