#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

realdir=$(dirname "$(realpath "$0")")

cd "${realdir}"

args="\
-Wall \
-Wcompat \
-Werror=incomplete-record-updates \
-Werror=incomplete-uni-patterns \
-Werror=missing-fields \
-Werror=partial-fields \
-Widentities \
-Wmissing-home-modules \
-Wredundant-constraints \
-fshow-warning-groups \
-O0 \
-threaded \
-rtsopts \
-with-rtsopts=-N \
"

set -x

nix-shell --run "ghc ${args} xmonad.hs -o ${1:-xmonad}"

rm -f ./*.hi ./*.o
