source "%val{config}/commands.kak"
source "%val{config}/filetype.kak"
source "%val{config}/hooks.kak"
source "%val{config}/mappings.kak"
source "%val{config}/options.kak"
try %{ source "%val{config}/haskell2.kak" }
try %{ source "%val{config}/dhall2.kak" }
source "%val{config}/plugins.kak"

# TODO: Remove comment character when joining lines
# TODO: Fix this in Markdown syntax highlighter (isn't highlighted as bold):
#       **Foo bar `baz`**
