#!/bin/sh

nnn_cd () {
  dir=$1

  if [ -z "$NNN_PIPE" ]; then
    echo "No pipe file found" >&2
    return
  fi

  if [ -n "$2" ]; then
    context=$2
  else
    context=0
  fi

  printf "%s" "$context$dir" > "$NNN_PIPE"
}
