#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Borders and gaps
bspc config border_width 2
bspc config window_gap 0

# Splitting
bspc config split_ratio 0.5
bspc config initial_polarity second_child

# Monocle mode
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Mouse
bspc config click_to_focus button1
bspc config swallow_first_click true
bspc config focus_follows_pointer true
