#!/bin/sh

sxhkd &
urxvtd &
urxvtc
setxkbmap -option caps:escape
xset r rate 150 30

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus button1
