#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if [ ! -e "./xmonad.hs" ]; then
  echo "Where's xmonad.hs?"
  exit 1
elif [ -L "./xmonad.hs" ]; then
  echo "You should run this from inside ~/dotfiles instead of ~/.xmonad"
  echo "(ghcid doesn't detect changes through a symlink)"
  exit 1
else
  nix-shell --run "ghcid xmonad.hs"
fi
