[colors]
background = "#ffffff"
foreground = "#002d38"
cursor_bg = "#8faaab"
cursor_fg = "#002d38"
cursor_border = "#8faaab"
selection_bg = "#f1e9d2"
selection_fg = "#002d38"
scrollbar_thumb = "#8faaab"
ansi = [
  "#093946",
  "#f23749",
  "#819500",
  "#ac8300",
  "#2b90d8",
  "#dd459d",
  "#259d94",
  "#f1e9d2",
]
brights = [
  "#002d38",
  "#d56500",
  "#5b7279",
  "#657377",
  "#98a8a8",
  "#7d80d1",
  "#8faaab",
  "#fbf7ef",
]
