[colors]
foreground = "#000000"
background = "#ffffff"
cursor_fg = "#000000"
cursor_bg = "#d1d5da"
cursor_border = "#d1d5da"
selection_fg = "#000000"
selection_bg = "#fff5b1"
scrollbar_thumb = "#d1d5da"
ansi = [
  "#24292e",
  "#cb2431",
  "#28a745",
  "#b08800",
  "#0366d6",
  "#6f42c1",
  "#ea4aaa",
  "#959da5",
]
brights = [
  "#444d56",
  "#ea4a5a",
  "#85e89d",
  "#f9c513",
  "#79b8ff",
  "#b392f0",
  "#f692ce",
  "#d1d5da",
]
