[colors]
foreground = "#ffffff"
background = "#010409"
cursor_fg = "#ffffff"
cursor_bg = "#b1bac4"
cursor_border = "#b1bac4"
selection_fg = "#000000"
selection_bg = "#f8e3a1"
scrollbar_thumb = "#b1bac4"
ansi = [
  "#21262d",
  "#da3633",
  "#3fb950",
  "#f2cc60",
  "#388bfd",
  "#bc8cff",
  "#f778ba",
  "#b1bac4",
]
brights = [
  "#484f58",
  "#ff7b72",
  "#7ee787",
  "#f8e3a1",
  "#79c0ff",
  "#d2a8ff",
  "#ff9bce",
  "#f0f6fc",
]
