#!/usr/bin/env bash
# shellcheck disable=SC2016

set -Eeuo pipefail
IFS=$'\n\t'

test -e ".git/hooks/pre-push" && ".git/hooks/pre-push"

if [ "$(git config evan.confirm-push || echo true)" = "false" ]; then
  exit 0
fi

remote_name=${1:-origin}

remote_location=${2:-"$(git remote get-url "${remote_name}")"}

repo=$(echo "${remote_location}" | sd '(?:git@github\.com:|https://github\.com/|git@git\.sr\.ht:~|https://git\.sr\.ht/~)([\w\-]+)/([\w\-\.]+)' '$1/$2' | sd '\.git$' '')

branch=$(git symbolic-ref HEAD | sd '(?:.+/)*(.+)' '$1')

delay=5

if echo "${branch}" | rg --quiet '^(master|main|trunk|development|release-.+)$'; then
  if [ -n "${repo}" ]; then
    read -p "Confirm repository (${repo}): " -r < /dev/tty
    if [ "${REPLY}" != "${repo}" ]; then
      echo "Incorrect repository name"
      exit 1
    fi
  fi

  read -p "Confirm branch (${branch}): " -r < /dev/tty
  if [ "${REPLY}" != "${branch}" ]; then
    echo "Incorrect branch name"
    exit 1
  fi

  if [ -n "${repo}" ]; then
    echo "Pushing to ${repo}:${branch} in ${delay} seconds... (Ctrl-C to cancel)"
  else
    echo "Pushing to ${branch} in ${delay} seconds... (Ctrl-C to cancel)"
  fi

  sleep "${delay}"
  exit 0
fi
