#!/usr/bin/env bash

# Config
user_dir="$HOME/.config/systemd/user"
system_dir="/etc/systemd/system"

name="$(basename "$(pwd)")"
install_dir=""

if ! [ -x "$(command -v stow)" ]; then
  echo "ERROR: stow is not installed" >&2
  exit 1
fi

if [ -z "$1" ]; then
  echo "ERROR: No install mode specified (must be 'user' or 'system')" >&2
  exit 1
fi

case "$1" in
  "user" ) install_dir="$user_dir";;
  "system" ) install_dir="$system_dir";;
  * ) echo "ERROR: Invalid install mode (must be 'user' or 'system')" >&2; exit 1;;
esac

if [ -n "$install_dir" ]; then
  set -x
  if [ "$1" = "user" ]; then
    mkdir -p "$user_dir"
  fi
  stow --dir ".." --target "$install_dir" -S "$name" --ignore "install"
fi
