#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

command -v git >/dev/null 2>&1 || (echo "Missing executable: git"; exit 1)

rude_emacs="${HOME}/.emacs.d"
xdg_emacs="${HOME}/.config/emacs"

echo "[doom] Installing Doom Emacs"
if [ ! -e "${xdg_emacs}" ]; then
  git clone --depth 1 "https://github.com/hlissner/doom-emacs" "${xdg_emacs}"
else
  echo "[doom] Existing Emacs installation at ${xdg_emacs}" >&2
  exit 1
fi

if [ ! -e "${rude_emacs}" ]; then
  "${xdg_emacs}/bin/doom" install
else
  echo "[doom] Existing Emacs installation at ${rude_emacs}" >&2
  exit 1
fi

echo "[doom] Setting up truecolor support"
emacs/.config/emacs/setup-truecolor
