#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if ! command -v brew >/dev/null 2>&1; then
  echo "[homebrew] Installing Homebrew"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "[homebrew] Installing packages"
brew bundle --no-lock --file homebrew/.Brewfile
