#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

source_path="${1:-${HOME}/dotfiles/nixos/configuration.nix}"
if [ -d "/persist" ]; then
  destination_path="/persist/etc/nixos/configuration.nix"
else
  destination_path="/etc/nixos/configuration.nix"
fi

confirm() {
  read -p "$1 [yN] " -n 1 -r >&2 < /dev/tty
  echo
  echo "${REPLY}" | grep --quiet --extended-regexp '^[Yy]$'
}

do_unstow() {
  # Undo GNU Stow's symlink
  rm -f "${HOME}/configuration.nix"
  rm -f "${HOME}/indigo-vm.nix"
}

do_exists() {
  test -e "${source_path}" \
    || (echo "Source path '${source_path}' doesn't exist" >&2; exit 1)

  test -e "${destination_path}" \
    || (echo "Destination path '${destination_path}' doesn't exist" >&2; exit 1)
}

do_copy() {
  if ! diff "${destination_path}" "${source_path}" >/dev/null; then
    diff -u "${destination_path}" "${source_path}" | eval "$(git config core.pager)"

    if confirm "Copy new configuration?"; then
      sudo cp -v "${destination_path}" "${destination_path}.old"
      sudo cp -v "${source_path}" "${destination_path}"
    fi
  else
    echo "No change between configurations" >&2
  fi
}

do_switch() {
  if confirm "Switch to configuration?"; then
    sudo nixos-rebuild -I nixpkgs="${HOME}/.nix-profile/channels/nixpkgs" switch
  else
    exit 0
  fi
}

do_unstow
do_exists
do_copy
do_switch
