[package]
name = "memorize"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-escapes = "0.1.1"
clap = { version = "4.3.19", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
