#!/bin/sh

set -euo pipefail

if [ -z "$BORG_REPO" ] || [ -z "$BORG_PASSPHRASE" ] || [ -z "$BORG_REMOTE_PATH" ]; then
  echo "Environment variables are not configured correctly" >&2
  exit 1
fi

mkdir -p ~/.config/borg/
{
  echo "BORG_REPO=$BORG_REPO"
  echo "BORG_PASSPHRASE=$BORG_PASSPHRASE"
  echo "BORG_REMOTE_PATH=$BORG_REMOTE_PATH"
} >> ~/.config/borg/env
