#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# Check if environment variables have been configured
if [ -z "$BORG_REPO" ] \
|| [ -z "$BORG_PASSPHRASE" ] \
|| [ -z "$BORG_REMOTE_PATH" ]; then
  echo "Environment variables are not configured correctly" >&2
  exit 1
fi

mkdir -p "$HOME/.config/borg/"

# Write environment variables to file
{
  echo "BORG_REPO=$BORG_REPO"
  echo "BORG_PASSPHRASE=$BORG_PASSPHRASE"
  echo "BORG_REMOTE_PATH=$BORG_REMOTE_PATH"
} >> "$HOME/.config/borg/env"
