#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

if [ -n "$(git status --porcelain)" ]; then
  git stash push --include-untracked --quiet
  trap "git stash pop --index --quiet" EXIT
fi

eval "$@"
