#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

  git log \
  --oneline \
  --pretty=format:'%Cred%h%Creset %s%C(yellow)%d%Creset %Cgreen(%cr)%Creset %Cblue<%an>%Creset' \
  --color=always \
| fzf -1 -0 \
  --exact \
  --query "$*" \
  --no-sort \
  --reverse \
  --height 100% \
  --preview "echo {} | cut -d ' ' -f 1 | xargs git show --color=always | delta" \
  --preview-window right:60%:noborder \
  --ansi \
  --color light \
| cut -d ' ' -f 1 \
| xargs git rev-parse --verify --quiet
