#!/usr/bin/env bash

set -eo pipefail

if [ -z "$1" ]; then
  # Fail when no arguments provided
  exit 1
elif echo "$1" | grep -Eq '^[0-9]+$'; then
  # If it's a number, work backwards from HEAD
  ref="HEAD~$1"
else
  # If it's not a number, treat it like a normal ref
  ref="$1"
fi

# Verify it's a valid ref
if git rev-parse "$ref" --verify --quiet >/dev/null 2>&1; then
  echo "Invalid ref '$ref'"
  exit 1
fi

# Begin interactive rebase
git rebase --interactive --gpg-sign "$ref" "${@:2}"
