#!/usr/bin/env bash

set -eo pipefail

if [ -z "$1" ]; then
  # Fail when no arguments provided
  exit 1
elif echo "$1" | grep -Eq '^[0-9]+$'; then
  # If it's a number, work backwards from HEAD
  git rebase --interactive "HEAD~$1" "${@:2}"
else
  # If it's not a number, treat it like a normal ref
  git rebase --interactive "$1" "${@:2}"
fi
