#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

if [ -z "${1:-}" ]; then
  # Fail when no argument provided
  echo "Missing revision or offset"
  exit 1
elif echo "$1" | grep -Eq '^[0-9]+$'; then
  # If it's a number, work backwards from HEAD
  rev="HEAD~$1"
else
  # If it's not a number, treat it like a normal revision
  rev="$1~1"
fi

# Verify it's a valid revision
if git rev-parse "${rev}" --verify --quiet >/dev/null 2>&1; then
  echo "Invalid revision '${rev}'"
  exit 1
fi

# Begin interactive rebase
git rebase --interactive "${rev}" "${@:2}"
