#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# TODO: Test this in anger
echo "TODO: Test this in concert with merge.autoStash"

if [ "$(git remote | wc -l)" -gt 1 ]; then
  echo "Multiple remotes, not sure which one to use:" >&2
  git remote
  exit 1
fi

branch_name=$(git branch --show-current)
remote_name=$(git remote)

git stash push --include-untracked --quiet

trap "git stash pop --index --quiet" EXIT

git fetch "${remote_name}" "${branch_name}"

git merge --squash

git commit --message "Merge '${remote_name}/${branch_name}'"
