snippet_support = false
verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes

[language.haskell]
filetypes = ["haskell"]
roots = ["cabal.project", "*.cabal", "stack.yaml", "package.yaml", "Setup.hs"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
