#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

_log() { echo -e "$@" >&2; }
_fail() { _log "Error: $*"; exit 1; }

exclude_file="${HOME}/.config/borg/exclude"
archive_name=${1:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
archive_root="${HOME}"

# Check that borg is installed
command -v borg >/dev/null 2>&1 \
  || _fail "borg is not installed, or is not in your PATH"

# Check that environment variables are configured
test -n "${BORG_REMOTE_PATH:-}" \
  || _fail "BORG_REMOTE_PATH has not been configured"
test -n "${BORG_REPO:-}" \
  || _fail "BORG_REPO has not been configured"
test -n "${BORG_PASSPHRASE:-}" \
  || _fail "BORG_PASSPHRASE has not been configured"

# Check that paths exist
test -f "${exclude_file}" \
  || _fail "Exclude file '${exclude_file}' does not exist, or is not a file"
test -d "${archive_root}" \
  || _fail "Archive root '${archive_root}' does not exist, or is not a directory"

# Check connection to rsync.net
wait=$(if [ "$(uname)" = "Darwin" ]; then echo "-W"; else echo "-w"; fi)
ping -c 2 "${wait}" 30 rsync.net >/dev/null 2>&1 \
  || _fail "Failed to connect to rsync.net"

_log "Creating archive named '${archive_name}'"

# Create archive
_log "Connecting to rsync.net..."
_log "(O)riginal size"
_log "(C)ompressed size"
_log "(D)eduplicated size"
_log "(N)umber of files processed"
borg \
  create \
  --verbose \
  --progress \
  --stats \
  --exclude-from "${exclude_file}" \
  --compression zstd,10 \
  ::"${archive_name}" \
  "${archive_root}"
_log "Finished creating archive"

# Prune
_log "Pruning"
borg \
  prune \
  --verbose \
  --stats \
  --save-space \
  --keep-hourly=24 \
  --keep-daily=30 \
  --keep-weekly=8 \
  --keep-monthly=12
_log "Pruned"
