#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

command -v yabai >/dev/null 2>&1 \
  || (echo "Missing 'yabai'" >&2; exit 1)

yabai -m config layout         bsp
yabai -m config top_padding    02
yabai -m config bottom_padding 02
yabai -m config left_padding   02
yabai -m config right_padding  02
yabai -m config window_gap     02

echo "Configured yabai!"
