#!/bin/sh

# color="dark"

# if [ "$(uname)" = "Linux" ]; then
#   os="linux"
# elif [ "$(uname)" = "Darwin" ]; then
#   os="macos"
# fi

# kitty \
#   --single-instance \
#   --instance-group "kitty" \
#   --config "$HOME/.config/kitty/kitty.conf" \
#   --config "$HOME/.config/kitty/$os.conf" \
#   --config "$HOME/.config/kitty/$color.conf"

kitty --single-instance --instance-group "kitty"
