source "%val{config}/purescript.kak" }

source "%val{config}/commands.kak" }
source "%val{config}/filetype.kak" }
source "%val{config}/hooks.kak" }
source "%val{config}/mappings.kak" }
source "%val{config}/options.kak" }
source "%val{config}/plugins.kak" }
