try %{ source "%val{config}/purescript.kak" }

source "%val{config}/commands.kak"
source "%val{config}/filetype.kak"
source "%val{config}/hooks.kak"
source "%val{config}/mappings.kak"
source "%val{config}/options.kak"
source "%val{config}/plugins.kak"

require-module "user_commands"
require-module "user_filetype"
require-module "user_hooks"
require-module "user_mappings"
require-module "user_options"
require-module "user_plugins"

# source "%val{config}/evanrelf.kak"
