#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

command -v curl >/dev/null 2>&1 \
  || (echo "Missing executable: curl"; exit 1)

if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
  echo "[neovim] Installing vim-plug"
  curl --location --fail --create-dirs \
    "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" \
    -o "$HOME/.local/share/nvim/site/autoload/plug.vim"
fi
