#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

command -v curl >/dev/null 2>&1 \
  || (echo "Missing executable: curl"; exit 1)

install_vim_plug() {
  if [ ! -f "${HOME}/.local/share/nvim/site/autoload/plug.vim" ]; then
    echo "[neovim] Installing vim-plug"
    curl --location --fail --create-dirs \
      "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" \
      -o "${HOME}/.local/share/nvim/site/autoload/plug.vim"
  fi
}

install_packer_nvim() {
  if [ ! -d "${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
    echo "[neovim] Installing packer.nvim"
    git clone "https://github.com/wbthomason/packer.nvim" \
      "${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  fi
}

install_packer_nvim
