#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

current_branch=$(git symbolic-ref HEAD | sed -e "s,.*/\(.*\),\1,")
blacklist_regex='^(master|main|release-.*)$'
delay=5

if echo "$current_branch" | grep --quiet --extended-regexp "$blacklist_regex"; then
  read -p "You're about to push to branch '$current_branch'. Is that what you intended? [yN] " -n 1 -r < /dev/tty
  echo
  if echo "$REPLY" | grep --quiet --extended-regexp '^[Yy]$'; then
    echo "Pushing to branch '$current_branch' in $delay seconds... (Ctrl-C to cancel)"
    sleep $delay
    exit 0
  else
    exit 1
  fi
fi
