#!/usr/bin/env bash

# Tweaked version of Edward Thomson's `mirror.sh` script:
# https://www.edwardthomson.com/blog/mirroring_git_repositories.html

set -Eeuo pipefail
IFS=$'\n\t'

if [ "$#" -ne 2 ]; then
  "Usage: git mirror <source> <target>" >&2
  exit 1
fi

source_repo="$1"
target_repo="$2"
dir=$(mktemp -d)

echo "Cloning '${source_repo}' into '${dir}'"

git init --bare "${dir}"
cd "${dir}"

git config remote.origin.url "${source_repo}"
git config --add remote.origin.fetch '+refs/heads/*:refs/heads/*'
git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
git config --add remote.origin.fetch '+refs/notes/*:refs/notes/*'
git config remote.origin.mirror true
git fetch --all

echo "Pushing to '${target_repo}'"

git push --mirror "${target_repo}"

rm -rf "${dir}"

echo "Done"
