#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

assert_exists() {
  command -v "$1" >/dev/null 2>&1 || (echo "can't find $1" >&2; exit 1)
}

assert_exists amixer
assert_exists grep
assert_exists head
assert_exists light
assert_exists date

main() {
  test -f "/sys/class/power_supply/BAT0/capacity" \
    || (echo "can't find battery capacity" >&2; exit 1)

  volume=$(amixer get Master | grep --extended-regexp --only-matching '[0-9]+%' | head -1)
  brightness=$(light -G | cut -d '.' -f 1)
  battery=$(cat /sys/class/power_supply/BAT0/capacity)
  date=$(date +'%Y-%m-%d %l:%M %p')

  echo "Volume: ${volume} | Brightness: ${brightness}% | Battery: ${battery}% | ${date}"
}

while main; do sleep 10; done
